digi/models.py
from digi import db
from flask_login import UserMixin
from datetime import datetime
#This file is responsible for creating the database models



class Photo(db.Model):
    __tablename__ = "photo"
    id = db.Column(db.Integer, primary_key=True)
    image_name = db.Column(db.String(400))
    name = db.Column(db.String(200))
    creation_date=db.Column(db.Date)

digi/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import (
    SubmitField,
    StringField,
    FileField,

)

from wtforms.validators import InputRequired

# this file has all the functions that create the different forms users 



class PhotoForm(FlaskForm):
    name = StringField("Title", )
    image = FileField("Cover Image",validators=[InputRequired()])
    submit = SubmitField("Submit")

digi/__init__.py
from flask import Flask 
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import os

db=SQLAlchemy(session_options={"autoflush":False})
#create a function that creates a web application
# a web server will run this web application

def init_db():
    """For use on command line for setting up
    the database.
    """

    db.drop_all()
    db.create_all()


def create_app():
    print(__name__)  
    app=Flask(__name__)  # this is the name of the module/package that is calling this app
    app.debug=True
    app.secret_key='dafdfsfgdhh'
    #config
    uri = os.getenv("DATABASE_URL")  # or other relevant config var
    if uri and uri.startswith("postgres://"):
        uri = uri.replace("postgres://", "postgresql://", 1)
    app.config['SQLALCHEMY_DATABASE_URI']=uri
    #init
    db.init_app(app)
    
    bootstrap=Bootstrap(app)
    
    #initialise the login manager
 



    from . import views
    app.register_blueprint(views.mainbp)  
    

    return app

digi/views.py
from flask import Blueprint, redirect, flash
from flask import render_template
from base64 import b64encode
from flask import request
from digi import db
from flask import Blueprint, render_template, redirect, url_for, session,flash
from functools import wraps
from digi.models import Photo
from sqlalchemy import desc
import os
from os import listdir
from os.path import isfile, join
from datetime import datetime
import random
from werkzeug.utils import secure_filename

#this file sets what the index route of the web application will be
mainbp = Blueprint("main", __name__)

site_password = 'big nuts'
admin_pass='zz'
mypath='C:\\Users\\eej\\Pictures'
# custome decorator to check password
def check_pw(func):
    @wraps(func)
    def decorated_function(*args, **kwargs):
        status = session.get('status')
        if status != "good":
            return redirect(url_for('main.login'))
        return func(*args, **kwargs)

    return decorated_function
#the index route is a search bar unless a search has been done in which case the function querys the database and fetches the results to display them

@mainbp.route("/<pagenum>")
@check_pw
def index(pagenum):  
    photos = Photo.query.order_by(desc(Photo.creation_date)).all()
    #random.shuffle(photos)
    listing=PageResult(photos,pagenum)
    print((listing.page))
    return render_template("bindex.html",listing=PageResult(photos,pagenum))
   
@mainbp.route("/")
def reroute():
    return redirect("/0")
class PageResult:
   def __init__(self, data, page = 1, number = 21):
     self.__dict__ = dict(zip(['data', 'page', 'number'], [data, page, number]))
     self.full_listing = [self.data[i:i+number] for i in range(0, len(self.data), number)]
   def __iter__(self):
     for i in self.full_listing[int(self.page)-1]:
       yield i
   def __repr__(self): #used for page linking
     return "/displayitems/{}".format(int(self.page)+1) #view the next page

@mainbp.route("/admin/<pagenum>")
@check_pw
def showalladmin(pagenum):
    photos = Photo.query.order_by(desc(Photo.creation_date)).all()
    random.shuffle(photos)
    listing=PageResult(photos,pagenum)
    print((listing.page))
    return render_template("adminindex.html",listing=PageResult(photos,pagenum))

@mainbp.route('/login', methods=['GET','POST'])
def login():
     if request.method == "POST":
            print("poggers")
            

            password = request.form.get('password')
            print(password)
            if password==admin_pass:
                session["status"] = 'good'
                return redirect("/admin/0")

            if password != site_password:
                flash('wrong password! try again...')
                return redirect(request.url)

            if password==site_password:
                session["status"] = 'good'
                print("yoooo")
                return redirect("/0")


     return render_template('login.html')
@mainbp.route("/add")
def add():
 
    onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))& f.endswith('.JPG')]
    for file in onlyfiles:
     photo = Photo(
              
                name=file,
                image_name=file,
                creation_date=datetime.today()       
            )
     db.session.add(photo)

    db.session.commit()

    return redirect("/0")

@mainbp.route("/delete/<int:id>")

def delete(id):
      photos = Photo.query.filter_by(id=id).first()
      print(photos)
      os.remove(os.getcwd()+ "\\digi\\static\\imgs\\"+ secure_filename(photos.image_name))
      db.session.delete(photos)
      db.session.commit()  
      return redirect("/0")

@mainbp.route("/post", methods=["GET", "POST"])
def create():
    #form = PhotoForm()

    # attaching the form users fill out to the function
    if request.method == "POST":
       
            uploaded_files = request.files['file']
                
            # add file names to file db and then save files to server
            uploaded_files.save(
                os.path.join(
                os.getcwd() + "\\digi\\static\\imgs",
                secure_filename(uploaded_files.filename),
                    )
                )
            print(request.form.get('name'))
            photo = Photo(
                        name=request.form.get('name'),
                        image_name=secure_filename(uploaded_files.filename),
                        creation_date=datetime.today()       
                    ) 
            db.session.add(photo)
                     
                    
            db.session.commit()  

               
                
                
   
            return redirect("/0")
    return render_template("uploader.html")

digi/templates/adminindex.html
{% extends "base.html" %}

{% block content %}

<div style="padding: 1.5rem;"></div>





     
     <div class="row justify-content-center">
     {% for photo in listing %}
     {% set list1 = photo.image_name.split('.') %}
       <div class="mb-5 mr-5 px-0 col-md-3 border" style="margin-left: 1rem; margin-right: 1rem;">
        <div class="card"  >
        <div class="card-header">
          <h4 class="my-0 font-weight-normal"style="text-align: center;">{{photo.image_name}}</h4>
        </div>
      
        <div class="card-body">
         
          {%set url='imgs/'+photo.image_name%}
          <img class="card-img-top" style=" width: 100%;
          height:20rem ;
         " src="{{url_for('static',filename=url)}}" alt="{{photo.name}}">
      </div>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{list1[0]}}">View Photo
    </button> 
      </div>
    </div>
    
    <div class="modal fade"  id="{{list1[0]}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" >
      <div class="modal-dialog"  role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{{photo.name}}</h5>
                  <button type="button" class="btn" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                  <img src="{{url_for('static',filename=url)}}" class="img-fluid">
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  <a download="{{photo.image_name}}" href="{{url_for('static',filename=url)}}"><button type="button" class="btn btn-primary" >Download</button></a>
                  <a href="{{url_for('main.delete', id=photo.id)}}"><button class="btn btn-primary">Delete</button></a>
              </div>
          </div>
      </div>
  </div>


       {% endfor %}
      </div>

      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">

          {%if listing.page|int >= 1%}
         
          <li class="page-item" >
            <a class="btn start-button  " href="/admin/{{listing.page|int-1}}">Prev</a></li>
          </li>
          {%endif%}
          
          <li class="page-item"style="margin-left:1rem">
            <a class="btn start-button  " href="/admin/{{listing.page|int+1}}">Next</a>
          </li>
        </ul>
      </nav>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
     
      {% endblock %}
   

digi/templates/base.html
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>digi dash</title>
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
       integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
       <link rel="shortcut icon" href="{{ url_for('static',filename='styles/icons/paint_old-0.png') }}" type="image/png">
       <link rel="stylesheet" href="{{ url_for('static',filename='styles/win95.css') }}">
     
  </head>
  <body class="container-fluid">
  
    <nav class="navbar navbar-expand-xl navbar-light navbar-95 py-3 "style="width:100%;justify-content: center;">
      <a class="navbar-brand" href="#" >
          <img src="{{ url_for('static',filename='styles/icons/computer-3.png') }}"> Digital Dash</a>
       
      
    
  </nav>
  {% block content %}
  {% endblock %}
</body>

</html>

digi/templates/bindex.html
{% extends "base.html" %}

{% block content %}

<div style="padding: 1.5rem;"></div>





     
     <div class="row justify-content-center">
     {% for photo in listing %}
     {% set list1 = photo.image_name.split('.') %}
       <div class="mb-5 mr-5 px-0 col-md-3 border" style="margin-left: 1rem; margin-right: 1rem;">
        <div class="card"  >
        <div class="card-header">
          <h4 class="my-0 font-weight-normal"style="text-align: center;">{{photo.name}}</h4>
        </div>
      
        <div class="card-body">
         {%set url='imgs/'+photo.image_name%}
         <img class="card-img-top" style=" width: 100%; height: 17rem; object-fit: cover;" src="{{url_for('static',filename=url)}}" alt="{{photo.name}}">
   
      </div>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#{{list1[0]}}">View Photo
    </button> 
      </div>
    </div>
    
    <div class="modal fade"  id="{{list1[0]}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" >
      <div class="modal-dialog"  role="document">
          <div class="modal-content">
              <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">{{photo.name}}</h5>
                  <button type="button" class="btn" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                  <img src="../static/imgs/{{photo.image_name}}" class="img-fluid">
              </div>
              <div class="modal-footer">
                  <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                  <a download="{{photo.image_name}}" href="../static/imgs/{{photo.image_name}}"><button type="button" class="btn btn-primary" >Download</button></a>
              </div>
          </div>
      </div>
  </div>


       {% endfor %}
      </div>

      <footer class="taskbar"style="left:0; right:0">
        <div class="container-fluid text-center text-md-left">

          <!-- Grid row -->
          <div class="row">
      
            <!-- Grid column -->
            <div class="col-md-1 mt-md-0 mt-3">
      
                <a href="https://github.com/AlexBSoft/win95.css" class="btn start-button"><img src="{{ url_for('static',filename='styles/icons/computer_win_lock-1.png')}}" class="icon-16">Theme</a>
                <a href="https://github.com/Ethan-gif/digidash/tree/main/digicamsite" class="btn start-button"><img src="{{ url_for('static',filename='styles/icons/directory_folder_options-5.png')}}" class="icon-16"> GitHub</a>
                
              </div>
              <div class="col-md-10 mb-md-0 mb-3">
          {%if listing.page|int >= 1%}
         
      
            <a class="btn start-button  " href="/{{listing.page|int-1}}">Prev</a></li>
            <a class="btn start-button  " href="/{{listing.page|int+1}}">Next</a>
        
            {%else%}
            <a class="btn start-button  " href="/{{listing.page|int+1}}">Next</a>
          {%endif%}
          </div>
    
           

          
        </div>

    </footer>
      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
     
      {% endblock %}
   

digi/templates/create.html
{% extends 'base.html' %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
  <div class="container">
    <div class="row mt-5">
      <div class="col-md-12">

        <h1>Add a new dotpoint</h1>
        {% if form.errors %}
    {{ form.errors }}
{% endif %}
{{ form.csrf_token }}
        {{wtf.quick_form(form)}}
        
      </div>
    </div>
  </div>

{% endblock %}

digi/templates/login.html
{% extends "base.html" %}

{% block content %}
<div style="padding: 1.5rem;"></div>
<div class="container">
    <div class="card mb-4">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Enter Password</h4>
        </div>
        <div style="padding:3rem"></div>
        <div class="card-body">
            <form method="POST" action="/login">
              
                <div class="form-group row">
                    <label for="inputPassword3" class="col-sm-2 col-form-label"><img src=" {{ url_for('static',filename='styles/icons/keys-0.png') }}" class="icon-16-4"> Password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-95" name="password">
                    </div>
                </div>
            
                <div class="form-group row">
                    <div style="padding:3rem"></div>
                    <div class="col-sm-10">
                        <button type="submit"  class="btn btn-primary">Sign in</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

digi/templates/showphoto.html
{% extends 'base.html' %}
{% block content %}  

<section >
  <div class="container ">
      <div class="row gx-4 gx-lg-5 align-items-center">
          <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="../static/{{photo.image_name}}" alt="{{photo.image_name}}" /></div>
          <div class="col-md-6">
             
              <h1 class="display-5 fw-bolder">{{photo.name}}</h1>
              
             <ul>
            
          </div>
             </ul>
            
            <div style="padding-top: 30px; padding-right: 300px;">
        
   
  </div>

          </div>
      </div>
  </div>
</section>

 
 
  
{% endblock %}  

digi/templates/uploader.html
{% extends "base.html" %}

{% block content %}
<div style="padding: 1.5rem;"></div>
<div class="container">
    <div class="card mb-4">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">Upload A New Photo</h4>
        </div>
      
        <div class="card-body">
            <form method="POST" action="/post"  enctype="multipart/form-data">
                <div class="form-group row">
                    <label for="inputEmail3" class="col-sm-2 col-form-label"><img src="{{ url_for('static',filename='styles/icons/computer_taskmgr-0.png') }}" class="icon-16-4"> Image Name</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-95" name="name" id="inputEmail3">
                    </div>
                    <div style="padding:1rem"></div>
         
                <div class="form-group row">
                    <label for="epicfile" class="col-sm-2 col-form-label"><img src=" {{ url_for('static',filename='styles/icons/directory_explorer-3.png') }}" class="icon-16-4"> Select a file</label>
                    <div class="col-sm-10">
                        <input type="file" name="file" class="form-control-file">
                    </div>
                </div>
            
                <div class="form-group row">
                    <div style="padding:3rem"></div>
                    <div class="col-sm-10">
                        <button type="submit"  class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}